### ISSUE TITLE
Allow disabling flattening

### ISSUE THREAD

**Issue by edgarrmondragon** [Widen/tap-rest-api-msdk#50]
Currently JSON arrays are string-ified. Users may want to output the raw JSON arrays, and many database targets, for example, support loading them into the appropriate array/variant column type.

**Comment by s7clarke10** [comment]
Hi @edgarrmondragon , I provided this option some time ago via this option.

        - name: store_raw_json_message
          kind: boolean

By default it is set to False but if it is set to True you get the whole raw JSON message. You can choose to only select a few string-ified fields alongside the raw JSON message.

**Comment by s7clarke10** [comment]
In reflection, I believe I should have added a bit more context.

There is an additional attribute added _SDC_RAW_JSON . This can be enabled via the boolean `store_raw_json_message` property being set to true. This field will contain the full JSON payload.

I left the rest of the discovered fields as because you may wish to retain a few of the discovered fields like an ID and LAST_MODIFIED_TIMESTAMP (depending on the API) as it is very useful for the incremental nature of retrieve data from an API and updating the state so you don't need to retrieve all the records.

For some API's like FHIR API, I select only the id, meta_lastUpdated, and the _sdc_raw_json.

If you wanted you could select only the _sdc_raw_json if you just want the JSON payload.

**Comment by edgarrmondragon** [comment]
That makes sense, those are helpful pointers for folks. Thanks as always @s7clarke10 🙏
